name: Budgets 1.0

on:
  workflow_dispatch:
  push:
    paths:
      - action.yml
      - .github/workflows/Module-Budgets-1.0.yml
      - Modules/Budgets/1.0/**
      - Scripts/**

env:
  VariableFilePath: global.variables.json
  TenantID: ${{ secrets.TENANT_ID }}
  AppID: ${{ secrets.APP_ID }}
  Subscription: ${{ secrets.SUBSCRIPTION }}
  AppSecret: ${{ secrets.APP_SECRET }}
  ModulesPath: Modules
  ModuleName: Budgets
  ModuleVersion: '1.0'

jobs:
  Validate:
    strategy:
      max-parallel: 1 # Avoid collision as parameters will be same
      matrix:
        os: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Load variables
        uses: equinor/AzVariables@v1

      - name: Connect to Azure
        uses: equinor/AzConnect@v1

      - name: Validate module
        uses: equinor/AzModules@v1
        with:
          Action: Validate
          ParameterFolderPath: ${{ env.ModulesPath }}/${{ env.ModuleName }}/${{ env.ModuleVersion }}/Parameters

      - name: Deploy module
        id: Deploy
        uses: equinor/AzModules@v1
        with:
          Action: Deploy
          ParameterFolderPath: ${{ env.ModulesPath }}/${{ env.ModuleName }}/${{ env.ModuleVersion }}/Parameters

      - name: 'Show Output'
        shell: pwsh
        run: |
          $Output = '${{ steps.Deploy.outputs.Output }}' | ConvertFrom-JSON
          $Output.PSObject.Properties | Select Name, Value | Format-Table -Wrap
